// <auto-generated />
using System;
using BoardApp.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BoardApp.Migrations
{
    [DbContext(typeof(BoardAppDbContext))]
    partial class BoardAppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BoardApp.Models.Board", b =>
                {
                    b.Property<int>("BoardNo")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BoardContent")
                        .IsRequired();

                    b.Property<string>("BoardTitle")
                        .IsRequired();

                    b.Property<string>("BoardWriter")
                        .IsRequired();

                    b.Property<DateTime>("CreatedDate");

                    b.Property<int>("ViewCount");

                    b.HasKey("BoardNo");

                    b.ToTable("Boards");
                });
#pragma warning restore 612, 618
        }
    }
}
